name: market_doctor
description: Community Health Care Revolution

version: 2.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_code_picker: ^3.0.0
  url_launcher: ^6.1.7
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.1
  file_picker: ^8.1.2
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.0.0 
  flutter_dotenv: ^5.0.2
  http: ^1.2.2
  font_awesome_flutter: ^10.0.0
  provider: ^6.0.3
  country_picker_pro: ^0.0.3
  country_icons: ^3.0.0
  fluttertoast: ^8.2.1
  shared_preferences: ^2.3.2
  table_calendar: ^3.0.8
  image_picker: ^1.1.2
  socket_io_client: ^3.0.0
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.2.1
  permission_handler: ^11.3.1
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/people.jpeg
    - assets/images/wheelchair.jpeg
    - assets/images/email-campaign.png
    - assets/images/medical-folder.png
    - assets/images/doctor-image.png
    - assets/icons/arrow_up.png
    - assets/images/people-celebrating.png
    - assets/images/medical-care.png
    - assets/icons/image.svg
    - assets/icons/document.svg
    - assets/images/location-review.png
    - assets/images/cases-image.png
    - assets/images/pills-image.png
    - assets/images/advert-image.png
    - assets/images/silh.png
    - assets/.env
    - assets/images/head.png
    - assets/images/chest.png
    - assets/images/stomach.png
    - assets/images/skin.png
    - assets/images/general.png


  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
